# Build environment for the dogecar Buildroot image.
# Host dependencies from https://buildroot.org/downloads/manual/manual.html#requirement
FROM docker.io/library/debian:trixie-20261005

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
        bash bc binutils build-essential bzip2 ca-certificates cpio curl \
        diffutils file findutils gawk git gzip libncurses-dev locales make \
        patch perl python3 rsync sed tar unzip wget xz-utils \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i 's/^# *en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen && locale-gen

ENV LANG=en_US.UTF-8
WORKDIR /work
